version: '3.7'
services:

  spending_app:
    image: anndi/spending_app:latest
    environment:
      - ACTIVE_PROFILE=prod
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    networks:
      - postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
