spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: true
    locations: classpath:test/migrations
    baseline-on-migrate: true
    validate-on-migrate: true
    verbose: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE