spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: postgres
    password: EyjMUYEyrOdIobHWiTmfihuyQGoNQgLT
    url: postgresql://postgres:EyjMUYEyrOdIobHWiTmfihuyQGoNQgLT@postgres.railway.internal:5432/spending