name: Build first pipeline for Spending app

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: build and deploy application
    runs-on: ubuntu-latest
    steps:
      - name: check the code
        uses: actions/checkout@v3

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: build jar
        run: |
          mvn clean
          mvn -B package -DskipTests --file pom.xml

      - name: build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spending-app:latest

      - name: login on dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spending-app:latest